package com.fcant.ss.mapper;

import com.fcant.ss.bean.Product;
import org.springframework.stereotype.Repository;

/**
 * ProductMapper
 *
 * encoding:UTF-8
 * @author Fcscanf
 * @date 上午 11:16 2019-07-31/0031
 */
@Repository
public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_product
     *
     * @mbg.generated Wed Jul 31 11:04:10 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_product
     *
     * @mbg.generated Wed Jul 31 11:04:10 GMT+08:00 2019
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_product
     *
     * @mbg.generated Wed Jul 31 11:04:10 GMT+08:00 2019
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_product
     *
     * @mbg.generated Wed Jul 31 11:04:10 GMT+08:00 2019
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_product
     *
     * @mbg.generated Wed Jul 31 11:04:10 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_product
     *
     * @mbg.generated Wed Jul 31 11:04:10 GMT+08:00 2019
     */
    int updateByPrimaryKey(Product record);
}