package com.fcant.ss.bean;

import lombok.Data;

/**
 * Product
 *
 * encoding:UTF-8
 * @author Fcscanf
 * @date 上午 11:07 2019-07-31/0031
 */
@Data
public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_product.id
     *
     * @mbg.generated Wed Jul 31 11:04:10 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_product.p_name
     *
     * @mbg.generated Wed Jul 31 11:04:10 GMT+08:00 2019
     */
    private String pName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_product.p_type
     *
     * @mbg.generated Wed Jul 31 11:04:10 GMT+08:00 2019
     */
    private String pType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_product.p_address
     *
     * @mbg.generated Wed Jul 31 11:04:10 GMT+08:00 2019
     */
    private String pAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_product.id
     *
     * @return the value of ss_product.id
     *
     * @mbg.generated Wed Jul 31 11:04:10 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_product.id
     *
     * @param id the value for ss_product.id
     *
     * @mbg.generated Wed Jul 31 11:04:10 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_product.p_name
     *
     * @return the value of ss_product.p_name
     *
     * @mbg.generated Wed Jul 31 11:04:10 GMT+08:00 2019
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_product.p_name
     *
     * @param pName the value for ss_product.p_name
     *
     * @mbg.generated Wed Jul 31 11:04:10 GMT+08:00 2019
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_product.p_type
     *
     * @return the value of ss_product.p_type
     *
     * @mbg.generated Wed Jul 31 11:04:10 GMT+08:00 2019
     */
    public String getpType() {
        return pType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_product.p_type
     *
     * @param pType the value for ss_product.p_type
     *
     * @mbg.generated Wed Jul 31 11:04:10 GMT+08:00 2019
     */
    public void setpType(String pType) {
        this.pType = pType == null ? null : pType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_product.p_address
     *
     * @return the value of ss_product.p_address
     *
     * @mbg.generated Wed Jul 31 11:04:10 GMT+08:00 2019
     */
    public String getpAddress() {
        return pAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_product.p_address
     *
     * @param pAddress the value for ss_product.p_address
     *
     * @mbg.generated Wed Jul 31 11:04:10 GMT+08:00 2019
     */
    public void setpAddress(String pAddress) {
        this.pAddress = pAddress == null ? null : pAddress.trim();
    }
}