package com.fcant.mybatis.ch01.mapper;

import com.fcant.mybatis.ch01.bean.Order;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Wed Jul 24 20:33:03 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Wed Jul 24 20:33:03 GMT+08:00 2019
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Wed Jul 24 20:33:03 GMT+08:00 2019
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Wed Jul 24 20:33:03 GMT+08:00 2019
     */
    Order selectByPrimaryKey(Integer orderId);

    /**
     * 根据ID获取Order信息-一般的查询,根据数据库表名列名
     *
     * @param orderId
     * @return order
     * @author Fcscanf
     * @date 下午 20:47 2019-07-24/0024
     */
    Order getOrderById(Integer orderId);

    /**
     * 根据ID获取Order信息-通过起别名查询
     *
     * @param orderId
     * @return order
     * @author Fcscanf
     * @date 下午 20:47 2019-07-24/0024
     */
    Order selectOrder(Integer orderId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Wed Jul 24 20:33:03 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Wed Jul 24 20:33:03 GMT+08:00 2019
     */
    int updateByPrimaryKey(Order record);
}